# Generated by Django 5.2.1 on 2025-10-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='designer', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('primary_color', models.CharField(default='#1A2634', max_length=7)),
                ('secondary_color', models.CharField(default='#F4F7F8', max_length=7)),
                ('accent_color', models.CharField(default='#FF6F61', max_length=7)),
                ('primary_font', models.CharField(default='Playfair Display', max_length=100)),
                ('secondary_font', models.CharField(default='Inter', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collection_covers/')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_popup', models.BooleanField(default=False)),
                ('popup_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectedDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('6months', '6 Months'), ('yearly', 'Yearly')], max_length=50, unique=True)),
                ('display_name', models.CharField(default='Standard Plan', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.IntegerField()),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paypal_plan_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='designer_portfolio.collection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='designs/covers/')),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('techpack_pdf', models.FileField(blank=True, help_text='Upload tech pack as PDF file', null=True, upload_to='designs/techpacks/pdf/')),
                ('techpack_excel', models.FileField(blank=True, help_text='Upload tech pack as Excel file', null=True, upload_to='designs/techpacks/excel/')),
                ('fabric_details', models.TextField(blank=True, help_text='Fabric specifications and requirements')),
                ('color_palette', models.CharField(blank=True, help_text='Color codes and descriptions', max_length=500)),
                ('size_range', models.CharField(blank=True, help_text='Available size range (e.g., XS-XL)', max_length=100)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Target retail price', max_digits=8, null=True)),
                ('production_notes', models.TextField(blank=True, help_text='Special production requirements or notes')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', help_text='Tell us about yourself and your design philosophy', max_length=1000)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='designers/profiles/')),
                ('portfolio_website', models.URLField(blank=True, help_text='Your personal website or portfolio')),
                ('instagram_handle', models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100)),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of design experience')),
                ('specialization', models.CharField(blank=True, help_text='e.g., Sustainable Fashion, Avant-garde, Streetwear', max_length=200)),
                ('education', models.CharField(blank=True, help_text='Educational background', max_length=300)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('available_for_collaborations', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Public contact email (optional)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designer Profile',
                'verbose_name_plural': 'Designer Profiles',
            },
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='designs/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designer_portfolio.design')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='events/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designer_portfolio.event')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Techpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric', models.CharField(blank=True, max_length=255)),
                ('trims', models.TextField(blank=True)),
                ('measurements', models.TextField(blank=True)),
                ('bom_file', models.FileField(blank=True, null=True, upload_to='techpacks/bom/')),
                ('notes', models.TextField(blank=True)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='techpack', to='designer_portfolio.design')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free_trial', 'Free Trial'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='free_trial', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe (Credit/Debit Card)'), ('paypal', 'PayPal'), ('applepay', 'Apple Pay')], max_length=20, null=True)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designer_portfolio.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/looks/')),
                ('fabric', models.CharField(blank=True, max_length=200, null=True)),
                ('measurements', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='designer_portfolio.collection')),
            ],
            options={
                'ordering': ['look_number'],
                'unique_together': {('collection', 'look_number')},
            },
        ),
    ]
