# Generated by Django 5.1.4 on 2026-02-13 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0004_add_chat_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this designer via invite link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
