# Generated by Django 5.2.1 on 2026-02-16 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0004_add_chat_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/profiles/')),
                ('bio', models.TextField(blank=True, default='')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('design_interests', models.CharField(blank=True, help_text='Comma-separated interests', max_length=500)),
                ('template_style', models.CharField(choices=[('clean', 'Clean'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='modern', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public (for recruiters)'), ('private', 'Private (classroom review only)')], db_index=True, default='private', max_length=20)),
                ('share_slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ui-ux', 'UI/UX'), ('graphic-design', 'Graphic Design'), ('animation', 'Animation'), ('product-design', 'Product Design'), ('branding', 'Branding'), ('illustration', 'Illustration'), ('other', 'Other')], db_index=True, default='ui-ux', max_length=40)),
                ('tools_used', models.CharField(blank=True, help_text='Comma-separated tools', max_length=255)),
                ('project_role', models.CharField(blank=True, max_length=120)),
                ('process_steps', models.TextField(blank=True, help_text='One process step per line, for example: Sketch -> Wireframe -> Final design')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='students/projects/images/')),
                ('process_video', models.FileField(blank=True, null=True, upload_to='students/projects/videos/')),
                ('project_pdf', models.FileField(blank=True, null=True, upload_to='students/projects/pdfs/')),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='designer_portfolio.studentportfolio')),
            ],
            options={
                'ordering': ['display_order', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_role', models.CharField(choices=[('teacher', 'Teacher'), ('peer', 'Peer')], default='peer', max_length=20)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_project_feedback', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='designer_portfolio.studentportfolioproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProjectBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='designer_portfolio.studentportfolioproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_project_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StudentProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='designer_portfolio.studentportfolioproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_project_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
