# Generated by Django 5.2.1 on 2025-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0005_design_additional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_notes',
            field=models.TextField(blank=True, help_text='Internal notes for review before publishing'),
        ),
    ]
