# Generated by Django 5.1.4 on 2026-02-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0005_studentportfolio_studentportfolioproject_and_more'),
        ('designer_portfolio', '0006_referral_system'),
    ]

    operations = [
    ]
