# Generated by Django 5.1.4 on 2026-02-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0007_merge_20260217_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('dress_type', models.CharField(blank=True, max_length=40)),
                ('dress_label', models.CharField(blank=True, max_length=100)),
                ('shoulder_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve_short', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve_wrist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fabric_type', models.CharField(blank=True, max_length=40)),
                ('fabric_label', models.CharField(blank=True, max_length=100)),
                ('wool_type', models.CharField(blank=True, max_length=40)),
                ('fabric_texture', models.CharField(blank=True, max_length=60)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dress_orders', to='designer_portfolio.designerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
