# Generated by Django 5.1.4 on 2026-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0008_dress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressorder',
            name='formal_subcategory',
            field=models.CharField(blank=True, help_text='Sub-category when Formal: suits, shirts, coats, jackets, etc.', max_length=60),
        ),
    ]
