# Generated by Django 5.2.1 on 2025-11-21 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0008_update_brand_palette'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdobeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('product_icon', models.CharField(blank=True, max_length=50)),
                ('adobe_product_id', models.CharField(blank=True, max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='DesignerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('question', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='includes_adobe_access',
            field=models.BooleanField(default=True, help_text='Whether this subscription includes Adobe Creative Suite access'),
        ),
        migrations.CreateModel(
            name='AdobePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('single', 'Single Product'), ('duo', '2 Products'), ('trio', '3 Products'), ('quad', '4 Products'), ('penta', '5 Products'), ('hexa', '6 Products'), ('full', 'Full Creative Suite')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('product_count', models.PositiveIntegerField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_products', models.ManyToManyField(blank=True, help_text='Recommended products for this package', to='designer_portfolio.adobeproduct')),
            ],
            options={
                'ordering': ['order', 'product_count'],
            },
        ),
        migrations.CreateModel(
            name='UserAdobeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('adobe_account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adobe_account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('adobe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer_portfolio.adobepackage')),
                ('selected_products', models.ManyToManyField(help_text='Products selected by user', to='designer_portfolio.adobeproduct')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adobe_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adobe Subscription',
                'verbose_name_plural': 'Adobe Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AdobeAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('login', 'Account Login'), ('download', 'Product Download'), ('usage', 'Product Usage'), ('support', 'Support Access')], default='login', max_length=50)),
                ('access_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('product_accessed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designer_portfolio.adobeproduct')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='designer_portfolio.useradobesubscription')),
            ],
            options={
                'verbose_name': 'Adobe Access Log',
                'verbose_name_plural': 'Adobe Access Logs',
                'ordering': ['-access_timestamp'],
            },
        ),
    ]
