# Generated by Django 5.1.4 on 2026-02-19 20:24

import secrets

import django.db.models.deletion
from django.db import migrations, models


def generate_access_tokens(apps, schema_editor):
    DressOrder = apps.get_model("designer_portfolio", "DressOrder")
    for order in DressOrder.objects.filter(access_token=""):
        order.access_token = secrets.token_urlsafe(32)
        order.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0009_add_formal_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressorder',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Viewer email for order confirmation and design access', max_length=254),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='design',
            field=models.ForeignKey(blank=True, help_text='Design linked to this order; only designer and order viewer can see it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dress_orders', to='designer_portfolio.design'),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('active', 'Active'), ('frozen', 'Frozen'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='free_trial', max_length=20),
        ),
        migrations.CreateModel(
            name='DressOrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], help_text='Status at time of this update (optional)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Designer notes (e.g. taking order, working on it)')),
                ('techpack_notes', models.TextField(blank=True, help_text='Techpack information about the order')),
                ('techpack_pdf', models.FileField(blank=True, help_text='Techpack PDF for this order', null=True, upload_to='orders/techpacks/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='designer_portfolio.dressorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(generate_access_tokens, migrations.RunPython.noop),
    ]
