# Generated by Django 5.1.4 on 2026-02-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0010_dress_order_status_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentportfolioproject',
            name='category',
            field=models.CharField(choices=[('fashion-design', 'Fashion Design'), ('editorial', 'Editorial & Lookbook'), ('collection', 'Collection'), ('ui-ux', 'UI/UX'), ('graphic-design', 'Graphic Design'), ('animation', 'Animation'), ('product-design', 'Product Design'), ('branding', 'Branding'), ('illustration', 'Illustration'), ('other', 'Other')], db_index=True, default='ui-ux', max_length=40),
        ),
        migrations.CreateModel(
            name='StudentPortfolioProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='students/projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='designer_portfolio.studentportfolioproject')),
            ],
            options={
                'ordering': ['display_order', '-created_at', 'id'],
            },
        ),
    ]
