# Generated by Django 5.2.1 on 2025-11-23 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0010_forumcategory_forumpost_forumtopic_forumpost_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(help_text='Address we can reply to.', max_length=254)),
                ('category', models.CharField(choices=[('website', 'Website improvement'), ('technical', 'Technical issue'), ('billing', 'Billing or subscription'), ('other', 'Other')], default='other', max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('page_url', models.CharField(blank=True, help_text='Optional page URL where the issue occurred.', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='open', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('reporter', models.ForeignKey(blank=True, help_text='Authenticated user who filed the report (if available).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
