# Generated by Django 5.1.4 on 2026-02-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0011_student_gallery_and_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPortfolioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=19.99, max_digits=8)),
                ('duration_days', models.IntegerField(default=30)),
                ('includes_custom_domain', models.BooleanField(default=True)),
                ('domain_free_years', models.PositiveIntegerField(default=2)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain (e.g. chpreddy.com). Requires Student Portfolio Pro.', max_length=253, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='domain_free_until',
            field=models.DateField(blank=True, help_text='Custom domain included free until this date (first 2 years for Pro).', null=True),
        ),
        migrations.CreateModel(
            name='StudentPortfolioSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='designer_portfolio.studentportfolioplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_portfolio_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Portfolio Subscription',
            },
        ),
    ]
