# Generated by Django 5.2.1 on 2026-02-27 21:02

import designer_portfolio.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0012_student_portfolio_pro_and_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerprofile',
            name='linkedin_profile',
            field=designer_portfolio.models.HTTPSURLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='portfolio_website',
            field=designer_portfolio.models.HTTPSURLField(blank=True, help_text='Your personal website or portfolio'),
        ),
        migrations.AlterField(
            model_name='eventcollaboration',
            name='portfolio_url',
            field=designer_portfolio.models.HTTPSURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='acquisition_initial_referrer',
            field=designer_portfolio.models.HTTPSURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='acquisition_landing_page',
            field=designer_portfolio.models.HTTPSURLField(blank=True, null=True),
        ),
    ]
