# Generated by Django 5.2.1 on 2025-11-30 20:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0013_designerprofile_default_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id', models.CharField(max_length=120)),
                ('template_name', models.CharField(max_length=200)),
                ('template_category', models.CharField(blank=True, max_length=120)),
                ('template_layout_key', models.CharField(blank=True, max_length=120)),
                ('template_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen copy of template JSON used at creation time.')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, choices=[('SS25', 'Spring / Summer 2025'), ('FW25', 'Fall / Winter 2025'), ('SS26', 'Spring / Summer 2026'), ('FW26', 'Fall / Winter 2026')], max_length=10)),
                ('product_type', models.CharField(choices=[('hoodie', 'Hoodie'), ('shell', 'Shell / Outerwear'), ('tee', 'Tee'), ('bottom', 'Bottom'), ('accessory', 'Accessory')], default='hoodie', max_length=40)),
                ('product_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('preview_copy', models.JSONField(blank=True, default=list, help_text='Short copy lines surfaced under the live preview.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('layout_key', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='designer_portfolio.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProductSpecField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('product_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='designer_portfolio.projectproductspec')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('layout_hint', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='designer_portfolio.project')),
            ],
            options={
                'ordering': ['order', 'stage_number'],
                'unique_together': {('project', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStageBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.CharField(max_length=300)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='designer_portfolio.projectstage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
