# Generated by Django 5.1.4 on 2026-06-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0013_alter_designerprofile_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='billing_interval',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='membership_tier',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
