# Generated by Django 5.2.1 on 2025-12-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0014_project_projectproductspec_projectproductspecfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('layout_key', models.CharField(max_length=120)),
                ('cover_title_placeholder', models.CharField(max_length=255)),
                ('cover_subtitle_placeholder', models.CharField(max_length=255)),
                ('summary', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_index', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('title_placeholder', models.CharField(max_length=200)),
                ('code_placeholder', models.CharField(blank=True, max_length=120)),
                ('default_views', models.JSONField(blank=True, default=list)),
                ('details_schema', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_blocks', to='designer_portfolio.template')),
            ],
            options={
                'db_table': 'template_product_blocks',
                'ordering': ['block_index', 'id'],
                'unique_together': {('template', 'block_index')},
            },
        ),
        migrations.CreateModel(
            name='TemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('default_items', models.JSONField(blank=True, default=list)),
                ('layout_hint', models.CharField(blank=True, max_length=120)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='designer_portfolio.template')),
            ],
            options={
                'db_table': 'template_stages',
                'ordering': ['stage_index', 'id'],
                'unique_together': {('template', 'stage_index')},
            },
        ),
    ]
