# Generated by Django 5.2.1 on 2025-12-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0015_template_templateproductblock_templatestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectproductspec',
            name='block_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectproductspec',
            name='code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectproductspec',
            name='default_views',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectproductspec',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectproductspec',
            name='template_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_products', to='designer_portfolio.templateproductblock'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='template_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stages', to='designer_portfolio.templatestage'),
        ),
    ]
