# Generated by Django 5.1.4 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContentBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_context', models.TextField(blank=True, help_text='Plain-text snapshot fed to the model (collections, designers, events).')),
                ('platforms', models.JSONField(default=dict, help_text='Keys: instagram_caption, instagram_hashtags, linkedin_post, x_post, suggested_cta, notes_for_designer')),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Social content bundle',
                'verbose_name_plural': 'Social content bundles',
                'ordering': ['-created_at'],
            },
        ),
    ]
