# Generated by Django 5.1.4 on 2026-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_social_content_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcontentbundle',
            name='bundle_kind',
            field=models.CharField(choices=[('hub_social', 'Hub (IG / LinkedIn / X)'), ('instagram_app', 'Instagram — designer iPhone app')], db_index=True, default='hub_social', max_length=32),
        ),
        migrations.AlterField(
            model_name='socialcontentbundle',
            name='platforms',
            field=models.JSONField(default=dict, help_text='hub_social: instagram_caption, instagram_hashtags, linkedin_post, x_post, … instagram_app: caption, hashtags, carousel_slides, stories_bullets, ai_designer_image_prompt, …'),
        ),
        migrations.AlterField(
            model_name='socialcontentbundle',
            name='source_context',
            field=models.TextField(blank=True, help_text='Plain-text snapshot fed to the model (site digest or iOS app facts).'),
        ),
    ]
