# Generated by Django 5.2.1 on 2026-05-07 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_social_bundle_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartnershipLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, help_text='Your role at the brand (e.g. Marketing Lead).', max_length=120)),
                ('website', models.URLField(blank=True)),
                ('partnership_kind', models.CharField(choices=[('competition', 'Design competition'), ('collab', 'Capsule / collaboration'), ('scholarship', 'Scholarship / grant'), ('mentorship', 'Mentorship sponsorship'), ('other', 'Something else')], default='competition', max_length=20)),
                ('audience_reach', models.CharField(blank=True, help_text="Audience you'd activate (e.g. '420K IG, 90K newsletter').", max_length=120)),
                ('message', models.TextField(blank=True, help_text="Brief on what you'd like to run with us.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand partnership lead',
                'verbose_name_plural': 'Brand partnership leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('meetup', 'Virtual meetup'), ('design_jam', 'Design jam')], db_index=True, default='webinar', max_length=16)),
                ('summary', models.CharField(blank=True, help_text='One-line elevator description shown on the events list.', max_length=240)),
                ('description_html', models.TextField(blank=True, help_text='Long-form description shown on the event detail page (HTML allowed).')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_label', models.CharField(blank=True, help_text="Display label, e.g. 'New York · EST'. Free text — no tz conversion.", max_length=64)),
                ('is_virtual', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, help_text="Venue or platform (e.g. 'Zoom', 'Discord stage', 'NYC studio').", max_length=200)),
                ('join_url', models.URLField(blank=True, help_text='Public join URL surfaced on the detail page once status is LIVE.')),
                ('host_name', models.CharField(blank=True, max_length=150)),
                ('host_bio', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Optional cap. Registration is closed once this is hit.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live now'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumInterestSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.CharField(blank=True, help_text='Optional: what they want forums to be (rooms, topics, etc.).', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forum interest signup',
                'verbose_name_plural': 'Forum interest signups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergingTalentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Headline shown on the feature card, e.g. 'Capsule by Maya R.'", max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('display_name', models.CharField(help_text='Designer name as it should appear publicly.', max_length=150)),
                ('designer_portfolio_url', models.URLField(blank=True, help_text='Public portfolio URL the feature card links to.')),
                ('hero_image_url', models.URLField(blank=True, help_text='Optional hero image (absolute URL).')),
                ('bio_html', models.TextField(blank=True, help_text='Short bio shown on the detail page (HTML allowed).')),
                ('success_story_html', models.TextField(blank=True, help_text="How they got noticed: brand they're now working with, contest win, capsule launch, etc. (HTML allowed).")),
                ('ordering', models.IntegerField(default=0, help_text='Lower numbers surface first on the list page.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer_user', models.ForeignKey(blank=True, help_text="Optional link to the designer's GDH account.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emerging_talent_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emerging talent feature',
                'verbose_name_plural': 'Emerging talent features',
                'ordering': ['ordering', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', 'Industry mentor'), ('mentee', 'Student / mentee')], db_index=True, max_length=10)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('headline', models.CharField(blank=True, help_text='Mentors: current job title + company. Mentees: school + year, or self-taught focus.', max_length=160)),
                ('focus_areas', models.CharField(blank=True, help_text="Comma-separated focus areas (e.g. 'tech packs, womenswear, denim').", max_length=240)),
                ('portfolio_url', models.URLField(blank=True)),
                ('availability', models.CharField(blank=True, help_text="Hours per month / time-zone (e.g. '2 hrs/mo · PT').", max_length=160)),
                ('message', models.TextField(blank=True, help_text="Mentors: why you want to mentor. Mentees: what kind of guidance you're looking for.")),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('active', 'Approved · waiting to match'), ('matched', 'Matched'), ('declined', 'Declined'), ('withdrawn', 'Withdrew')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship application',
                'verbose_name_plural': 'Mentorship applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Optional context the attendee wants the host to know.')),
                ('cancel_token', models.CharField(default=marketing.models._generate_event_token, max_length=64, unique=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='marketing.event')),
            ],
            options={
                'verbose_name': 'Event registration',
                'verbose_name_plural': 'Event registrations',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
