# Generated by Django 5.2.1 on 2026-05-08 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_community_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergingTalentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_url', models.URLField(help_text='Public portfolio URL (LinkedIn, personal site, drden portfolio).')),
                ('school', models.CharField(blank=True, help_text="School + program (e.g. 'Parsons · BFA Fashion Design').", max_length=200)),
                ('grad_year', models.CharField(blank=True, help_text="Year (e.g. '2026 final year', 'recent grad').", max_length=40)),
                ('focus_areas', models.CharField(blank=True, help_text="Comma-separated focus areas (e.g. 'tailoring, denim, womenswear').", max_length=240)),
                ('story', models.TextField(blank=True, help_text="Tell us about your work, your aesthetic, and why you'd be a fit.")),
                ('consent_share', models.BooleanField(default=False, help_text='Designer consents to drden publishing the feature.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('under_review', 'Under review'), ('approved', 'Approved · feature drafted'), ('declined', 'Declined'), ('withdrawn', 'Withdrew')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='marketing.emergingtalentfeature')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emerging_talent_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emerging Talent submission',
                'verbose_name_plural': 'Emerging Talent submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
