# Generated by Django 5.2.1 on 2026-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_emergingtalentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcontentbundle',
            name='bundle_kind',
            field=models.CharField(choices=[('hub_social', 'Hub (Facebook / IG / LinkedIn / X / YouTube)'), ('instagram_app', 'Instagram — designer iPhone app')], db_index=True, default='hub_social', max_length=32),
        ),
        migrations.AlterField(
            model_name='socialcontentbundle',
            name='platforms',
            field=models.JSONField(default=dict, help_text='hub_social: facebook_post, instagram_caption, instagram_hashtags, linkedin_post, x_post, youtube_post, … instagram_app: caption, hashtags, carousel_slides, stories_bullets, ai_designer_image_prompt, …'),
        ),
    ]
